Vagrant.configure("2") do |config|
    config.vm.define "webServer" do |webServer|
      webServer.vm.box_download_insecure = true
      webServer.vm.box = "ubuntu/bionic64"
      webServer.vm.network "forwarded_port", guest: 8080, host: 80
      webServer.vm.network "forwarded_port", guest: 22, host: 22
      webServer.vm.network "private_network", ip: "100.0.0.10"
      webServer.vm.hostname = "webServer"
      webServer.vm.provider "virtualbox" do |v|
        v.name = "webServer"
        v.memory = 2048
        v.cpus = 2
      end
    end
  
  end